### ISSUE TITLE
Make it fly

### ISSUE THREAD

**Issue by MikeInnes** [one-more-minute/JuliaDistro#1]
Remaining tasks:
- [x] LT/Plugin/Julia bundle
- [ ] Windows Installer
- [x] Bug fixes
- [x] Boot polish
- [x] Signed binaries

**Comment by ViralBShah** [comment]
We also need to have `@doc` working in 0.3 through Compat, and once that is done, encourage package developers to start using it. Eventually, over a few months, we will have quality documentation that can be integrated in the IDE.

Is a Mac dmg generation script already in place?  That should be easy to do too.

**Comment by MikeInnes** [comment]
I don't have a .dmg, just a .app (which at the moment I'm zipping up). I'll look into it

**Comment by ViralBShah** [comment]
That is easy. See `julia/contrib/mac/app/Makefile`. We do the following for base julia:

```
hdiutil create Julia-$(VERSION_SUFFIX).dmg -size 200m -ov -volname "Julia" -imagekey zlib-level=9 -srcfolder dmg
```

**Comment by MikeInnes** [comment]
Ok great, thanks. I'll just throw that into the build script then.

I just need to polish things up a tiny bit more and I'll publish some binaries for a sneak preview.

**Comment by staticfloat** [comment]
Note that the `-size 200m` parameter is a little finnicky.  If you set it too small, (even if the size of the objects inside the dmg themselves are quite small) it might fail with a strange error.

**Comment by MikeInnes** [comment]
Good to know, thanks.

By the way, why use dmg over a plain zip file? Just curious.

**Comment by staticfloat** [comment]
Honestly, mostly just because that's what most mac users expect.  I imagine there is an advantage if your files have resource forks or something exotic like that, since a .dmg file contains a filesystem rather than just a list of files, but beyond that I don't have any justification.  (And I don't think that argument even matters for Julia anyway)

**Comment by staticfloat** [comment]
Oh, also, you can have fancy folder backgrounds and whatnot that pop up, which is pretty common with installer .dmgs.  Things like folder backgrounds that say "drag this file to Applications to install", and which have a symlink to Applications inside of the .dmg.

**Comment by MikeInnes** [comment]
Well, that's a good enough reason for me :) I'll look into fancy backgrounds

**Comment by MikeInnes** [comment]
Ok, I've got some binaries ready for people to try out – see [here](http://discuss.junolab.org/t/new-juno-julia-bundles/13) for downloads. Feedback very welcome.

@tkelman, you were having issues with LT on Windows before – it'd be great if you have a moment to try out the new binaries and let me know how it goes.

@ihnorton, I think we should be roughly on track to getting an installer going. If you're able to make any headway on this it would be enormously helpful, otherwise any pointers are appreciated. I'll give you commit access to this repo, let me know what you think.

**Comment by tkelman** [comment]
@one-more-minute is it using the latest version of LT that @kenny-evitt was asking me to try in https://github.com/LightTable/LightTable/issues/1339#issuecomment-66531522 ? Haven't gotten a chance yet but would be good to kill 2 birds with one download.

**Comment by MikeInnes** [comment]
Yes and no, a while back we released a version with a newer node-webkit but it had issues and we had to roll back. I believe that's what @kenny-evitt was referring too. My distro is actually based on the [atom-shell branch](https://github.com/LightTable/LightTable/pull/1756), which solves the same issues in a different way.

The upshot of that is that you should see your issues fixed and a nice performance boost, exclusive to Julia :)
